apiVersion: v1
kind: Service
metadata:
  name: app6-rollout-active
  namespace: default
spec:
  selector:
    app: app6-rollout  # Points to the current active rollout
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
