apiVersion: v2
name: test-app-helm-umbrella-chart
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: umbrella-chart
    alias: my-app
    version: 2.0.0
    repository: https://danielticu.github.io/helm-umbrella-chart/

