# Specific values for test-app-helm-umbrella-chart.
my-app:
  replicaCount: 3

  image:
    repository: nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.14.0"