apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielticu/helm-test.git
    targetRevision: HEAD
    path: applications  # A directory containing application manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
    ignoreDifferences:
      - group: "*"
        kind: "Application"
        namespace: "*"
        jsonPointers:
          # Allow manually disabling auto sync for apps, useful for debugging.
          - /spec/syncPolicy/automated
          # These are automatically updated on a regular basis. Not ignoring last applied configuration since it's used for computing diffs after normalization.
          - /metadata/annotations/argocd.argoproj.io~1refresh
          - /operation
