apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app5
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielticu/helm-test.git
    targetRevision: HEAD
    path: java-microservice
    helm:
      valueFiles:
        - "../values/default-values.yaml"
        - "../values/test/test-values.yaml"
        - "../values/test/athena/athena-values.yaml"
        - "../values/test/athena/app4-values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
