apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app6-rollout
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/danielticu/helm-test.git
    targetRevision: HEAD
    path: rollout
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
