apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/danielticu/helm-test.git
    targetRevision: HEAD
    path: my-argocd-apps
    helm:
      valueFiles:
        - "applications/{{ .Values.appName }}/values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
