apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-apps
  namespace: default
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | default "https://github.com/danielticu/helm-test.git" }}
    targetRevision: {{ .Values.targetRevision | default "HEAD" }}
    path: {{ .Values.global.path }}
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
