apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-helm
  namespace: default
spec:
  project: default

  source:
    repoURL: https://danielticu.github.io/helm-test/
    chart: test-app-helm
    targetRevision: "0.3.0"

  destination:
    server: https://kubernetes.default.svc
    namespace: test-app-helm

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true